# Generated by Django 6.0 on 2026-06-26 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 26, 12, 38, 15, 967128)),
        ),
    ]
