# Generated by Django 6.0 on 2026-10-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
